### PR TITLE
enable (dir input) or (files input) using dir scan to scan when dir being input

### PR DESCRIPTION
**Pull request by chanmaoganda**
i make a feature of enabling scan directory or input files.
I use scan_dir to scan when dir is inputted.
Also, dir input together with files input is not allowed

### CODE REVIEW

**Comment by chanmaoganda** [comment]
i am not native English speaker.
apologies for my poor english

**Comment by iqiziqi** [comment]
Does this feature duplicate existing feature?

Now  we can use glob to resolve a directory input

For example:

```
ncmdump ~/Downloads/**/*.ncm
```

**Comment by chanmaoganda** [comment]
but why not add this feature to make easier usage?
In fact, we can even use shell script to grab all ncm files and pass them into the program.
But adding this feature makes simpler usage

**Comment by iqiziqi** [comment]
I don't think duplicate features should be added.

**Comment by iqiziqi** [comment]
Perhaps we should add some clarification in the documentation and in the command line help. 
🤔

**Comment by chanmaoganda** [comment]
That' s also an considerate idea 😊

**Comment by iqiziqi** [comment]
OK. Then I'll close this PR and add this clarification in the next release.

**Pull request closed without merging**
